### ISSUE TITLE
Notice resource in 2.0.0

### ISSUE THREAD

**Issue by mat3k** [murraysum/honeybadger-api#26]
After updating to 2.0.0 version i've encountered problem with notice resource. After calling `paginate` method on `Notice` i'm receiving error

```
2.3.1 :001 > Honeybadger::Api::Notice.paginate(XXXX, XXXX)
NoMethodError: undefined method `[]' for nil:NilClass
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/deploy.rb:14:in `initialize'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/notice.rb:22:in `new'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/notice.rb:22:in `initialize'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/notice.rb:42:in `new'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/notice.rb:42:in `block in handler'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/paginator.rb:22:in `block in initialize'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/paginator.rb:21:in `map'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/paginator.rb:21:in `initialize'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/request.rb:40:in `new'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/request.rb:40:in `paginate'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/request.rb:36:in `paginate'
	from gems/honeybadger-api-2.0.0/lib/honeybadger-api/notice.rb:37:in `paginate'
	from (irb):1
```

From what i see, Notice resource is now using Deploy resource. Why Deploy is 
obligatory now ?

EDIT 1
I think empty deploy key in response is causing that problem

**Comment by murraysum** [comment]
Hey @mat3k ,

As part of the upgrade to v2 of the Read API I noticed the gem was missing a deploy attribute on the notices resource. Unfortunately, I didn't realise that the deploy attribute isn't always returned by the API and should be optional.

Thanks for reporting. I'll put together a release to make the deploy attribute optional on the notices resource..

**Comment by murraysum** [comment]
Hey @mat3k 

That should be a new release pushed out which should resolve your problem:

- https://github.com/murraysum/honeybadger-api/releases/tag/v2.0.1
- https://rubygems.org/gems/honeybadger-api/versions/2.0.1

Please let me know if you have any further issues. Thanks again 👍

**Comment by mat3k** [comment]
@murraysum Big thanks for such fast reaction. Gonna give feedback tomorrow.

**Comment by murraysum** [comment]
@mat3k No problem at all 😄
